version: '3'

services:
  elastic:
    container_name: elastic_museum
    image: elasticsearch:8.14.3
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: false
    ports:
      - 9200:9200
      - 9300:9300

  postgres:
    container_name: postgres_museum
    restart: always
    image: postgres
    command: ''
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=museum
      - POSTGRES_PASSWORD=mypassword

  redis:
    container_name: redis_museum
    image: "redis:alpine"

  web:
    restart: always
    depends_on:
      - postgres
      - elastic
      - redis
    volumes:
      - .:/app:cached
      - gem_cache:/gems
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development

volumes:
  gem_cache:
