test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

timeweb:
  service: S3
  access_key_id: <%= Settings.storage.access_key %>
  access_key_id: <%= Settings.storage.secret_key %>
  region: <%= Settings.storage.region %>
  bucket: <%= Settings.storage.bucket %>
